<<<<<<< HEAD
# Generated by Django 3.1.4 on 2020-12-28 16:48
=======
# Generated by Django 2.1.15 on 2021-01-03 23:44
>>>>>>> 85b83f186ebda63997a0c1fec6c7a34475271310

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('destination_id', models.AutoField(primary_key=True, serialize=False)),
                ('postal_code', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=50)),
                ('country_code', models.CharField(max_length=3)),
                ('date_from', models.DateTimeField(blank=True, null=True)),
                ('date_to', models.DateTimeField(blank=True, null=True)),
                ('n', models.FloatField()),
                ('e', models.FloatField()),
                ('budget', models.IntegerField()),
            ],
            options={
                'db_table': 'destination',
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('interest_id', models.AutoField(primary_key=True, serialize=False)),
                ('interest', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'interest',
            },
        ),
        migrations.CreateModel(
            name='Like_Dislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField()),
            ],
            options={
                'db_table': 'like/dislike',
            },
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('suggestion_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'suggestion',
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('transport_id', models.IntegerField(primary_key=True, serialize=False)),
                ('transport_type', models.CharField(max_length=15)),
                ('ticket', models.IntegerField()),
            ],
            options={
                'db_table': 'transport',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('trip_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'trip',
            },
        ),
    ]
