<<<<<<< HEAD:restapi/migrations/0002_auto_20201228_1748.py
# Generated by Django 3.1.4 on 2020-12-28 16:48
=======
# Generated by Django 2.1.15 on 2021-01-03 23:44
>>>>>>> 85b83f186ebda63997a0c1fec6c7a34475271310:restapi/migrations/0002_auto_20210104_0044.py

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='destination_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.Destination'),
        ),
        migrations.AddField(
            model_name='like_dislike',
            name='suggestion_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.Suggestion'),
        ),
        migrations.AddField(
            model_name='like_dislike',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='destination',
            name='trip_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.Trip'),
        ),
    ]
